services:
  app:
    container_name: golden-raspberry-awards
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=dev
    command: sh -c "npm run start:dev"
